### ISSUE TITLE
NPM packages incorrect

### ISSUE THREAD

**Issue by mitchogaard** [NeverwinterMoon/angular-swipe#1]
![image](https://cloud.githubusercontent.com/assets/1392855/15734658/94d7442e-2857-11e6-8983-ed70e4038c74.png)

This seems incorrect. Your version dates are all the same except for 0.4.0. Also, it looks as though they're all the same code. I'm trying to get a version via NPM without ES6 syntax and it's not possible because it seems like all of the packages point to the same source.

**Comment by NeverwinterMoon** [comment]
![image](https://cloud.githubusercontent.com/assets/1917308/15776446/368b1668-2990-11e6-962e-b9b1c074f51b.png)

Yes, versions of 0.1.0 to 0.3.0 were done in one day and the sources are actually different - I was updating readme file mostly and npm repo only refreshes its cache of readme if the version is different, so I had to bump it.

Also, the whole idea of my fork of this project was to move it to npm module style (it was using bower before) and to have cleaner code, including moving to ES6. ES5 version (marmorkuchen-net/angular-swipe) didn't support npm at all, at least at the time.

TL;TR This, npm version of the project, never had support for ES5.

**Comment by mitchogaard** [comment]
Ah I see. Thanks for the explanation. Unfortunately our project can't support ES6 yet; but that's my problem, not yours.
